apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpZeApNVFF6TVRKYUZ3MDBNekF4TWpZeE1UUXpNVEphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDNGUwVUpNc3EzekcwUDduZ2p0MlBrK0tIMzhwQXl5bE01QkE0b0xnbFRJQlIwQnMvUQpreW1BWm0zRVY5L3dKYUllNUtMKzMybUFLbmVUakhhZnlSZkNjazI0QXc3anowVWR3MGl6RlRJL3N5ank4eThtClJZczc1ekVSL0hkZHB1SEw3aVBpNnpUcnhPUi9GV05US1QxRFFsNjN3YjNhQ1Y3bHMwbmlpY3oyUDFTMHdqTzUKWjNMSEFnU2lnam5Qc1dSdDhpZy85aWIwdDdpanhsQ2ZteXY2VFByT3JzV2JKeThNNnpYaSt5WDYvZ2s3ODZSaQp4NlZvM1F2ODJEVnUxZXVMdUU2bS83b2o2U1NJSkE0WjlPbTZ4dnJpZnExR0lGZjFzS20vWFM3TmNqVzJ2K3RQCm9BaGJwT2ZBbGtuWWpQdGNySlEwQW1ZUmgwaXBIRW9MbEtVekFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNEeXpOb0xLWlZSN1E2bWhHWQpuTCtrTG4yN3V6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFVb2JCSTJYdDBVNVg0MXRPMHk2Zlp1Q1FzTk9NCkt5TVZRWjVkNHBnOWg5ZGQ5VUlheFlwaTU3b1VmUFZHU3V5a1pxeWEvcUpLZnYxMjhYeGNDeURQcldvdzZhS2sKNDBPalVGZ0E3Q0RlTFp6V2pGcmc2Q2xMSmxkbXhLdjNDNmZzbE5HbWR1TmFVbXdBa3ZUaGZaa1o5MHU4Z1o4RAo0bEZQQmljSmV2T3JBQVMvMGk4SjdUL3pXa2xQb0xOZkFVQnd0cmhxanJ0NklxQ2hab3daV08wM3NnZmQ3c3VBCnMzM1lyWjZzalMwdkt5ZTRXMitxQys3LzdPeUc5WUMvZGF2MDRObVV0dHByWTJzcVNDdkNLcVBDbDB4N0UvN3oKTkpkeVNQVWl4SUVXcG1BME81OGphLy94R1dZUHJ5MTZaZEJncVR4SkVvVk9remdic0dHb1pVSXA3Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://113fc7d6-bf6c-4239-9555-860d394f29ba.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_ad0719531000ba455cc398295f32c61d03eb5ea6f3f2e8954992e2024ce3f808
